fail_fast: false #: https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, "4"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: \.vscode
        args: [--autofix, --indent=4, --no-ensure-ascii, --no-sort-keys]
